# Generated by Django 5.2.6 on 2025-10-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('cong-nghe', '💻 Công Nghệ'), ('toan-hoc', '🔢 Toán Học'), ('ngoai-ngu', '🌍 Ngoại Ngữ'), ('van-hoc', '📖 Văn Học'), ('khoa-hoc', '🔬 Khoa Học'), ('kinh-te', '💰 Kinh Tế')], max_length=100, null=True),
        ),
    ]
