# Generated by Django 5.2.6 on 2025-10-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_level',
            field=models.CharField(choices=[('basic', 'Cơ bản'), ('standard', 'Tiêu chuẩn'), ('premium', 'Cao cấp')], default='basic', max_length=20),
        ),
    ]
