# Generated by Django 5.2.6 on 2025-10-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_membership_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn gói'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_upgrade_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày nâng cấp gói'),
        ),
    ]
